# Generated by Django 2.2.18 on 2021-03-18 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_lettera', models.CharField(max_length=255, unique=True)),
                ('mittente', models.CharField(max_length=255)),
                ('destinatario', models.CharField(max_length=255)),
                ('luogo_di_spedizione', models.CharField(max_length=255)),
                ('data_di_spedizione', models.DateField(auto_now=True)),
                ('luogo_di_conservazione', models.CharField(max_length=255)),
                ('fondo', models.CharField(max_length=255)),
                ('numerazione', models.IntegerField(choices=[('0', 0), ('1', 1)])),
                ('numero_prima_carta', models.IntegerField()),
                ('Facciata_prima_carta', models.CharField(choices=[('r', 'r'), ('v', 'v')], max_length=1)),
                ('numero_totale_facciate', models.IntegerField()),
                ('tipologia_lettera', models.CharField(choices=[('copia', 'copia'), ('originale', 'originale')], max_length=255)),
                ('presenza_nota_di_ricezione', models.IntegerField(choices=[('0', 0), ('1', 1)])),
                ('presenza_indirizzo', models.IntegerField(choices=[('0', 0), ('1', 1)])),
                ('presenza_filigrana', models.IntegerField(choices=[('0', 0), ('1', 1)])),
                ('presenza_sigillo', models.IntegerField(choices=[('0', 0), ('1', 1)])),
                ('presenza_firma', models.IntegerField(choices=[('0', 0), ('1', 1)])),
                ('altezza', models.IntegerField()),
                ('larghezza', models.IntegerField()),
                ('dimensioni', models.CharField(max_length=255)),
                ('trascrittore', models.CharField(max_length=255)),
                ('testo', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Recommender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_lettera', models.CharField(max_length=255, unique=True)),
                ('similar_ID', models.CharField(max_length=255)),
                ('similarity_value', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_lettera', models.CharField(max_length=255, unique=True)),
                ('top_words', models.CharField(max_length=255)),
                ('n_words', models.IntegerField()),
            ],
        ),
    ]
