# Generated by Django 2.2.18 on 2021-03-18 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='dimensioni',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='recommender',
            name='similar_ID',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='recommender',
            name='similarity_value',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='top_words',
            field=models.TextField(),
        ),
    ]
