# Generated by Django 2.2.18 on 2021-03-18 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20210318_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='numerazione',
            field=models.CharField(choices=[('0', '0'), ('1', '1')], max_length=1),
        ),
        migrations.AlterField(
            model_name='letter',
            name='presenza_filigrana',
            field=models.CharField(choices=[('0', '0'), ('1', '1')], max_length=1),
        ),
        migrations.AlterField(
            model_name='letter',
            name='presenza_firma',
            field=models.CharField(choices=[('0', '0'), ('1', '1')], max_length=1),
        ),
        migrations.AlterField(
            model_name='letter',
            name='presenza_indirizzo',
            field=models.CharField(choices=[('0', '0'), ('1', '1')], max_length=1),
        ),
        migrations.AlterField(
            model_name='letter',
            name='presenza_nota_di_ricezione',
            field=models.CharField(choices=[('0', '0'), ('1', '1')], max_length=1),
        ),
        migrations.AlterField(
            model_name='letter',
            name='presenza_sigillo',
            field=models.CharField(choices=[('0', '0'), ('1', '1')], max_length=1),
        ),
    ]
