# Generated by Django 2.2.18 on 2021-03-18 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_auto_20210318_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='numerazione',
            field=models.FloatField(choices=[(0.0, 0.0), (1.0, 1.0)]),
        ),
        migrations.AlterField(
            model_name='letter',
            name='presenza_filigrana',
            field=models.FloatField(choices=[(0.0, 0.0), (1.0, 1.0)]),
        ),
        migrations.AlterField(
            model_name='letter',
            name='presenza_firma',
            field=models.FloatField(choices=[(0.0, 0.0), (1.0, 1.0)]),
        ),
        migrations.AlterField(
            model_name='letter',
            name='presenza_indirizzo',
            field=models.FloatField(choices=[(0.0, 0.0), (1.0, 1.0)]),
        ),
        migrations.AlterField(
            model_name='letter',
            name='presenza_nota_di_ricezione',
            field=models.FloatField(choices=[(0.0, 0.0), (1.0, 1.0)]),
        ),
        migrations.AlterField(
            model_name='letter',
            name='presenza_sigillo',
            field=models.FloatField(choices=[(0.0, 0.0), (1.0, 1.0)]),
        ),
    ]
