# Generated by Django 2.2.18 on 2021-03-18 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20210318_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='numerazione',
            field=models.IntegerField(choices=[('0', '0'), ('1', '1')]),
        ),
        migrations.AlterField(
            model_name='letter',
            name='presenza_filigrana',
            field=models.IntegerField(choices=[('0', '0'), ('1', '1')]),
        ),
        migrations.AlterField(
            model_name='letter',
            name='presenza_firma',
            field=models.IntegerField(choices=[('0', '0'), ('1', '1')]),
        ),
        migrations.AlterField(
            model_name='letter',
            name='presenza_indirizzo',
            field=models.IntegerField(choices=[('0', '0'), ('1', '1')]),
        ),
        migrations.AlterField(
            model_name='letter',
            name='presenza_nota_di_ricezione',
            field=models.IntegerField(choices=[('0', '0'), ('1', '1')]),
        ),
        migrations.AlterField(
            model_name='letter',
            name='presenza_sigillo',
            field=models.IntegerField(choices=[('0', '0'), ('1', '1')]),
        ),
    ]
