# Generated by Django 2.2.18 on 2021-03-26 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_auto_20210318_1507'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempLetter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_lettera', models.CharField(max_length=255, unique=True)),
                ('mittente', models.CharField(max_length=255)),
                ('destinatario', models.CharField(max_length=255)),
                ('luogo_di_spedizione', models.CharField(max_length=255)),
                ('data_di_spedizione', models.DateField(auto_now=True)),
                ('luogo_di_conservazione', models.CharField(max_length=255)),
                ('fondo', models.CharField(max_length=255)),
                ('numerazione', models.FloatField(choices=[(0.0, 0.0), (1.0, 1.0)])),
                ('numero_prima_carta', models.IntegerField()),
                ('Facciata_prima_carta', models.CharField(choices=[('r', 'r'), ('v', 'v')], max_length=1)),
                ('numero_totale_facciate', models.IntegerField()),
                ('tipologia_lettera', models.CharField(choices=[('copia', 'copia'), ('originale', 'originale')], max_length=255)),
                ('presenza_nota_di_ricezione', models.FloatField(choices=[(0.0, 0.0), (1.0, 1.0)])),
                ('presenza_indirizzo', models.FloatField(choices=[(0.0, 0.0), (1.0, 1.0)])),
                ('presenza_filigrana', models.FloatField(choices=[(0.0, 0.0), (1.0, 1.0)])),
                ('presenza_sigillo', models.FloatField(choices=[(0.0, 0.0), (1.0, 1.0)])),
                ('presenza_firma', models.FloatField(choices=[(0.0, 0.0), (1.0, 1.0)])),
                ('altezza', models.IntegerField()),
                ('larghezza', models.IntegerField()),
                ('dimensioni', models.TextField()),
                ('trascrittore', models.CharField(max_length=255)),
                ('testo', models.TextField()),
                ('corrected', models.BooleanField(default=False)),
            ],
        ),
    ]
